bachelorette/urls.py
from django.conf import settings
# from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import TemplateView
from global_funcs import views as globalfuncviews

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='home.html')),
    url(r'',include('questions.urls', namespace='questions')),
    url(r'^reset/', globalfuncviews.reset_app, name ='reset_app'),
]

questions/urls.py
from django.conf.urls import url
from questions import views

app_name = 'questions'

urlpatterns = [
    url(r'^interface', views.ControlView.as_view(), name="control_panel"),
    url(r'^place/(?P<pk>\d+)/$', views.PlaceDetail.as_view(), name='place_detail'),
    url(r'^place/success/(?P<pk>\d+)/$', views.SuccessView.as_view(), name='success_view'),
    url(r'^place/fail/(?P<pk>\d+)/$', views.FailView.as_view(), name='fail_view'),
    url(r'^thanks/$', views.ThanksView.as_view(), name='thanks_view'),
    url(r'^bonus/$', views.BonusView.as_view(), name='bonus_view'),
]

questions/models.py
from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.

class Place(models.Model):
    place_id = models.PositiveIntegerField(primary_key=True)
    next_id = models.PositiveIntegerField(default=0)
    instructions = models.TextField(default='')
    plank_clue = models.TextField(default='')
    plank_prompt = models.TextField(default='')
    name_of_establishment = models.CharField(max_length=100)
    plank_answer = models.CharField(max_length=100)
    is_current = models.BooleanField(default=False)
    location_complete = models.BooleanField(default = False)

    def __str__(self):
        return str(self.name_of_establishment)

questions/forms.py
from django import forms
from django.core import validators
from . import models


class ClueForm(forms.Form):
    answer = forms.CharField(required=True)

global_funcs/views.py
from django.http import HttpResponseForbidden, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import render

from questions.models import Place


def reset_app(request):
    # print('hi there')
    for place in Place.objects.all():
        place.location_complete = False
        place.is_current = False
        place.save()
    #set the first location as current
    first_place = Place.objects.get(place_id=1)
    first_place.is_current = True
    first_place.save()

    return render(request, 'home.html')

questions/views.py
from django import forms
from django.http import HttpResponseForbidden, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views.generic.edit import FormMixin
from django.shortcuts import render
from django.views.generic import (View, TemplateView,
                                  CreateView, DetailView,
                                  ListView)
from . import models
from .forms import ClueForm
# Create your views here.

class ControlView(ListView):
    model = models.Place
    context_object_name = 'places'
    template_name = 'questions/control_panel.html'
    def get_context_data(self, **kwargs):
        ctx = super(ControlView, self).get_context_data(**kwargs)

        quantity_complete = models.Place.objects.filter(location_complete = True).count()
        total_quantity = models.Place.objects.count()

        try:
            currentquestion = models.Place.objects.get(is_current = True)
        except:
            currentquestion = models.Place.objects.get(place_id = total_quantity)
        currentid = currentquestion.place_id

        ctx['percentage'] = round(quantity_complete/total_quantity * 100)
        ctx['currentquestion'] = currentid
        return ctx

class PlaceDetail(DetailView):
    model = models.Place
    context_object_name = 'place'
    template_name = 'questions/placedetail.html'

    def post(self, request, *args, **kwargs):
        clue_form = ClueForm(data=request.POST)
        if clue_form.is_valid():
            answer = clue_form.cleaned_data['answer']
            place = self.get_object()
            # did someone already answer this?
            if place.location_complete == True:
                return HttpResponseRedirect(reverse("questions:control_panel"))
            else:
                answer = answer.replace(' ', '').lower()
                plankanswer = place.plank_answer.replace(' ', '').lower()

                # did they get the right answer?
                if answer == plankanswer:
                    print(answer)
                    place.location_complete = True
                    place.is_current = False
                    place.save()
                    if place.next_id != 0:
                        nextplace = models.Place.objects.get(place_id = place.next_id)
                        nextplace.is_current = True
                        nextplace.save()
                    return HttpResponseRedirect(reverse("questions:success_view", kwargs={'pk':place.next_id}))
                else:
                    return HttpResponseRedirect(reverse("questions:fail_view", kwargs={'pk':place.place_id}))
                return HttpResponseRedirect(reverse("questions:control_panel"))
        else:
            return HttpResponseRedirect(reverse("questions:control_panel"))
    def get_context_data(self, **kwargs):
        ctx = super(PlaceDetail, self).get_context_data(**kwargs)
        ctx['clueform'] = ClueForm()
        return ctx



class SuccessView(TemplateView):
    template_name = 'questions/success.html'
    def get_context_data(self, **kwargs):
        ctx = super(SuccessView, self).get_context_data(**kwargs)
        ctx['nextpk'] = self.kwargs['pk']
        return ctx


class FailView(TemplateView):
    template_name = 'questions/fail.html'
    def get_context_data(self, **kwargs):
        ctx = super(FailView, self).get_context_data(**kwargs)
        ctx['samepk'] = self.kwargs['pk']
        return ctx


class ThanksView(TemplateView):
    template_name = 'questions/thanks.html'



class BonusView(TemplateView):
    template_name = 'questions/bonus.html'

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bachelaurax</title>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- font-awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">


  </head>
  <body>

      {% block content %}
      {% endblock %}



  </body>
  <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
</html>

templates/base2.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bachelaurax</title>


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- font-awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">


  </head>
  <body>

      {% block content %}
      {% endblock %}



  </body>
  <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
</html>

templates/home.html
{% extends "base.html" %}
{% load static%}

{% block content %}
<div class="container homepage_container" style="background-repeat: repeat;
                                            background-size: cover;">
<div class="container">
  <div class="row">
    <div class="col-sm-12 text-center homepage_div table_parent">
      <div class="table_child">
        <h1 style="color: white; margin-bottom: 20px;">Welcome to the Bachelorette Party!</h1>
        <a  href="/interface"><button class="btn btn-success">Start the Journey</button></a>
        <!-- <img src="{% static 'img/elephant_background.jpg' %}" alt="myelephant"> -->

      </div><!-- table_child-->

    </div><!-- col-sm-12 -->
  </div><!-- row -->

</div>


{% endblock %}

templates/questions/bonus.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block content %}

  <div class="container">
    <div class="row">
      <div class="col-sm-12 subpage_div table_parent" id = "bonus_page" style="
                                      background-repeat: repeat;
                                      background-size: cover;
                                      background-position: center;
                                      height: 100vh;">

      <a href="/interface" style="position: absolute; right: 15px; top: 15px;"><img src="{% static 'img/sloth_icon.png' %}" alt="sloth_icon" style="height: 50px;"></a>


        <div class="table_child">
          <div id="percentage_div" style="background-color: rgba(1, 1, 1, 0.4); padding: 10px 10px;">
            <h4 style="color: white;">Here's a couple more things to do:</h4>
            <ul style="color: white;">
              <li>There's a dog petting event at Ellwood Thompson @ 5pm (call them before you go and confirm)</li>
              <li>Swing by "The Daily" for some awesome cocktails.</li>
              <li>Tons of clothing places including "Trend", "Phoenix",  "Lex's", and "Vintage Clothing".</li>
              <li>Check out the Chop Suey book shop! (I'll say they don't have much of a mythology collection though)</li>
              <li>Visit "Cool Colors Gallery" for some interesting bird artwork.</li>
            </ul>
          </div>


        </div> <!--middle aligned stuff -->

      </div><!--subpage_div-->


    </div><!-- row -->


  </div><!--container -->

{% endblock %}

templates/questions/control_panel.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-sm-12 subpage_div table_parent" id ="homepage_slothdiv" style="background-repeat: repeat;
                                                                                  background-size: cover;">

    <a href="" style="position: absolute; right: 15px; top: 15px;"><img src="{% static 'img/sloth_icon.png' %}" alt="sloth_icon" style="height: 50px;"></a>
    <a href="/reset" style="position: absolute; left: 15px; top: 20px;" id="reset_button"><i class="fa fa-refresh" aria-hidden="true"></i> Reset Progress</a>

      <div class="table_child">
        <div style="margin-top: -60px; margin-bottom: 30px; background-color: rgba(1, 1, 1, 0.5); padding: 10px 10px;" id="percentage_div">
          <h1 style="color: white;">Bachelorettes have completed {{percentage}}%</h1>
        </div>


        <div class="btn-group">
          <div style = "margin-right: 20px;" class="dropdown">
            <a class="btn btn-secondary dropdown-toggle" href="" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Places
            </a>

            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              {% for place in places %}
                {% if place.location_complete == True or place.is_current == True%}
                <a class="dropdown-item" href="{% url 'questions:place_detail' pk=place.place_id %}">{{place.name_of_establishment}}</a>
                {% endif %}
              {% endfor %}

            </div>
          </div>

          <a href="{% url 'questions:place_detail' pk=currentquestion %}" ><button class="btn btn-secondary">Current</button></a>
          {% if percentage == 100%}
          <a href="{% url 'questions:bonus_view' %}" style="margin-left: 20px;"><button class="btn btn-primary">Bonus</button></a>
          {%endif%}
        </div><!-- btn-group -->

      </div>

    </div>
    <div class="col-sm-12 subtext_area " style = "background-color: rgba(1, 1, 1, 0.5); color: white; padding-top: 10px;">
      <p style="font-size: 14px;">This is your dashboard. You can always tap the sloth to review past questions and see your current percentage. Answers are not case/space sensitive.
           <br><span style="font-size: 10px;">(1. Sloths are awesome  2. That's why they are here  3. Deal with it.)<span></p>
    </div>
  </div>

</div>


{% endblock %}

templates/questions/fail.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block content %}

  <div class="container">
    <div class="row">
      <div class="col-sm-12 subpage_div table_parent" style="background-image: url('');
                                      background-repeat: repeat;
                                      background-size: cover;">

      <a href="/interface" style="position: absolute; right: 15px; top: 15px;"><img src="{% static 'img/sloth_icon.png' %}" alt="sloth_icon" style="height: 50px;"></a>


        <div class="table_child text-center">
            <h1 style="margin-bottom: 30px;" >Sorry, you missed it <br>:(</h1>
            <a href="{% url 'questions:place_detail' pk=samepk %}"><button class='btn btn-success'>Doesn't mean you can't try again!</button></a>
        </div> <!--middle aligned stuff -->

      </div><!--subpage_div-->

      <!-- FOOTER AREA for notes-->
      <div class="col-sm-12 subtext_area " style = "background-color: rgba(1, 1, 1, 0.5); color: white; padding-top: 10px;">
        <p>Keep trying, I'm sure you guys can get it.  However, if things get really frustrating, give me a call and I'll help you out.  My number is 202-320-5859.</p>
      </div>


    </div><!-- row -->


  </div><!--container -->

{% endblock %}

templates/questions/placedetail.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block content %}

  <div class="container">
    <div class="row">
      <div class="col-sm-12 subpage_div table_parent" style="background-image: url('{% static 'img/baby_sloth.png' %}');
                                      background-repeat: repeat;
                                      background-size: cover;">

      <a href="/interface" style="position: absolute; right: 15px; top: 15px;"><img src="{% static 'img/sloth_icon.png' %}" alt="sloth_icon" style="height: 50px;"></a>


        <div class="table_child">

          <h2 style = "margin-bottom: 30px;">{{place.name_of_establishment}}</h2>

          <h4 style = "margin-bottom: 30px;">{{place.plank_clue}}</h4>
          <h4>{{place.plank_prompt}}</h4>

          <form method="post">
            {% csrf_token %}
            {% if place.location_complete %}
              <fieldset disabled>
              {{ clueform.answer|add_class:"form-control"}}
              <input style = "margin-top: 15px;" class="btn btn-success" type="submit" value="Submit">
              <h4 style="color: #5cb85c; margin-top: 15px;">You got this right!  The answer was {{place.plank_answer}}</h4>
              </fieldset>
            {% else %}
              {{ clueform.answer|add_class:"form-control"}}
              <input style = "margin-top: 15px;" class="btn btn-success" type="submit" value="Submit">
            {% endif%}
          </form>


        </div> <!--middle aligned stuff -->

      </div><!--subpage_div-->

      <!-- FOOTER AREA for notes-->
      <div class="col-sm-12 subtext_area " style = "background-color: rgba(1, 1, 1, 0.5); color: white; padding-top: 10px;">
        <p>Instructions: {{place.instructions}}</p>
      </div>


    </div><!-- row -->


  </div><!--container -->

{% endblock %}

templates/questions/success.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block content %}

  <div class="container">
    <div class="row">
      <div class="col-sm-12 subpage_div table_parent" style="background-image: url('');
                                      background-repeat: repeat;
                                      background-size: cover;">

      <a href="/interface" style="position: absolute; right: 15px; top: 15px;"><img src="{% static 'img/sloth_icon.png' %}" alt="sloth_icon" style="height: 50px;"></a>


        <div class="table_child text-center">
            <h1 style="margin-bottom: 30px;" >YOU'RE AWESOME!</h1>
            {% if nextpk == '0' %}
              <a href="{% url 'questions:thanks_view' %}"><button class='btn btn-success'>You freakn' did it!</button></a>
            {% else %}
              <a href="{% url 'questions:place_detail' pk=nextpk %}"><button class='btn btn-success'>Find out where you're going next!</button></a>
            {% endif %}
        </div> <!--middle aligned stuff -->

      </div><!--subpage_div-->

      <!-- FOOTER AREA for notes-->
      <div class="col-sm-12 subtext_area " style = "background-color: rgba(1, 1, 1, 0.5); color: white; padding-top: 10px;">
        <p></p>
      </div>


    </div><!-- row -->


  </div><!--container -->

{% endblock %}

templates/questions/thanks.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block content %}

  <div class="container">
    <div class="row">
      <div class="col-sm-12 subpage_div table_parent" style="background-image: url('');
                                      background-repeat: repeat;
                                      background-size: cover;">

      <a href="/interface" style="position: absolute; right: 15px; top: 15px;"><img src="{% static 'img/sloth_icon.png' %}" alt="sloth_icon" style="height: 50px;"></a>


        <div class="table_child text-center">
            <h1 style="margin-bottom: 30px;" >I have to congratulate you for getting through this.  You made it through the product of sleep deprivation, coffee, and baby carrots. </h1>
            <h1><i>Bravo</i></h1>

        </div> <!--middle aligned stuff -->

      </div><!--subpage_div-->

      <!-- FOOTER AREA for notes-->
      <div class="col-sm-12 subtext_area " style = "background-color: rgba(1, 1, 1, 0.5); color: white; padding-top: 10px;">
        <p>You'll notice a little easter egg on the front page.</p>
      </div>


    </div><!-- row -->


  </div><!--container -->

{% endblock %}